/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BuildPc: typeof import('./src/components/buildPc.vue')['default']
    ContactUs: typeof import('./src/components/contactUs.vue')['default']
    CustomizeDialog: typeof import('./src/components/customizeDialog.vue')['default']
    FindParts: typeof import('./src/components/FindParts.vue')['default']
    GetAdvice: typeof import('./src/components/getAdvice.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VRow: typeof import('vuetify/lib')['VRow']
  }
}
